name: Build Linux Container Image and Push to ACR

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: multitdockeracr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Get latest release
      run: |
        RELEASE=$(curl -s https://api.github.com/repos/junnuvenu/nginx_proj/releases/latest)
    - name: Extract tag from release
      run: |
        TAG=$(echo $RELEASE | jq -r '.tag_name')
        echo "Latest tag is $TAG"
    - name: Login to ghcr.io
      run: |
        echo "${{ secrets.GHCR_TOKEN }}" | docker login --username "${{ secrets.USERNAME }}" --password-stdin ghcr.io
    - name: Pull image from ghcr.io
      run: |
        docker pull ghcr.io/junnuvenu/nginx_proj:$TAG
    - name: push to ACR
      run: |
        docker tag ghcr.io/junnuvenu/nginx_proj:$TAG "multitdockeracr.azurecr.io/nginx_proj:$TAG"
        docker push multitdockeracr.azurecr.io/nginx_proj:$TAG
