name: Build Linux Container Image and Push to ACR

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
       
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: multitdockeracr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build . -t multitdockeracr.azurecr.io/nginx_proj:${{ github.sha }}
        docker push multitdockeracr.azurecr.io/nginx_proj:${{ github.sha }}
