name: Deploy GHCR Image

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy GHCR Image
        uses: azure/vm-deployment@v1
        with:
          resource-group: rg-delta-devops
          vm-name: multi-tenant-application-docker-test-vm
          image-url: docker pull ghcr.io/junnuvenu/nginx:latest
          admin-username: azureuser
          admin-password: Venu12345678
