name: Deploy to Azure VM

on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AUTH_SECRET }}
      - uses: azure/vm-deployment@v1
        with:
          resource-group: rg-delta-devops
          vm-name: multi-tenant-application-docker-test 
          image-url: ghcr.io/junnuvenu/nginx:latest
          image-type: container
