name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Login to ghcr.io
      run: |
        echo "${{ secrets.GHCR_TOKEN }}" | docker login --username "${{ secrets.USERNAME }}" --password-stdin ghcr.io
    - name: Pull image from ghcr.io
      run: |
        if [[ "refs/heads/master" =~ refs/tags/ ]]; then
        if [[ "refs/heads/master" =~ refs/tags/ ]]; then
        TAG="refs/heads/master"
        else
         TAG="651a480981bb4d7f870079e5cc98393c223a2f0b";
        fi
         docker pull ghcr.io/***/nginx_proj:$TAG
         shell: /usr/bin/bash -e {0}

    - name: Login to ACR
      run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login --username "${{ secrets.ACR_USERNAME }}" --password-stdin "${{ secrets.ACR_LOGIN_SERVER }}"
    - name: Deploy image to ACR
      run: |
        docker tag ghcr.io/junnuvenu/nginx_proj:$TAG "${{ secrets.ACR_LOGIN_SERVER }}/nginx_proj:$TAG"
        docker push "${{ secrets.ACR_LOGIN_SERVER }}/nginx_proj:$TAG"

