name: Deploy to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
          azcliversion: 2.300.2
          inlineScript: |
            az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }} -s ${{ secrets.SUBSCRIPTION_ID }}
    - name: Deploy to Azure VM
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az vm extension set \
            --resource-group rg-delta-devops \
            --vm-name multi-tenant-application-docker-test-vm \
            --name DockerExtension \
            --publisher Microsoft.Azure.Extensions \
            --version 2.0 \
            --settings '{"docker": {"image": "ghcr.io/junnuvenu/nginx_proj:latest"}}'
